name: cv_maker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  # state
  flutter_bloc: ^9.1.1
  provider: ^6.1.4
  # others
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  flutter_keyboard_visibility: ^6.0.0
  # db
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  # pdf
  share_plus: ^10.1.4
  pdf: ^3.11.3
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  # vip
  purchases_flutter: ^8.7.4
  purchases_ui_flutter: ^8.7.4
  # firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
  fonts:
    # Inter
    - family: inter400
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: inter500
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: inter700
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: inter900
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    # Funnel
    - family: funnel400
      fonts:
        - asset: assets/fonts/FunnelDisplay-Regular.ttf
    - family: funnel500
      fonts:
        - asset: assets/fonts/FunnelDisplay-Medium.ttf
    - family: funnel600
      fonts:
        - asset: assets/fonts/FunnelDisplay-SemiBold.ttf
    - family: funnel700
      fonts:
        - asset: assets/fonts/FunnelDisplay-Bold.ttf
    - family: funnel800
      fonts:
        - asset: assets/fonts/FunnelDisplay-ExtraBold.ttf
    # Gotham
    - family: gotham400
      fonts:
        - asset: assets/fonts/gotham-regular.ttf
    - family: gotham700
      fonts:
        - asset: assets/fonts/gotham-Bold.ttf
    - family: gotham900
      fonts:
        - asset: assets/fonts/gotham-Black.ttf