name: cv_maker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  share_plus: ^10.1.4 # export
  # purchases_flutter: ^8.7.0 # pro
  pdf: ^3.11.3
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/templates/
  # fonts:
  #   - family: medium
  #     fonts:
  #       - asset: assets/fonts/Inter-Medium.ttf
  #   - family: bold
  #     fonts:
  #       - asset: assets/fonts/Inter-Bold.ttf
  #   - family: black
  #     fonts:
  #       - asset: assets/fonts/Inter-Black.ttf
  #   - family: dosis
  #     fonts:
  #       - asset: assets/fonts/Dosis-Bold.ttf
  #   - family: sf
  #     fonts:
  #       - asset: assets/fonts/SFProText-Regular.ttf
