// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBcN4z8SHFs-rwoYIOrm72LnRzlv_fa3Ng',
//     appId: '1:75952618266:android:2bc589415f6dbff043caa3',
//     messagingSenderId: '75952618266',
//     projectId: 'cv-maker-c5a3d',
//     storageBucket: 'cv-maker-c5a3d.firebasestorage.app',
//   );

//   const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB3uI7TpdemZxQX24CMgbxtnk8_s8ZPA98',
//     appId: '1:75952618266:ios:b254e49ac055197043caa3',
//     messagingSenderId: '75952618266',
//     projectId: 'cv-maker-c5a3d',
//     storageBucket: 'cv-maker-c5a3d.firebasestorage.app',
//     iosBundleId: 'com.helperg.resume.builder',
//   );
// }
